// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35vSaUYRi6-uU3rV5iXkd_9PznuBaJcw',
    appId: '1:867722950685:web:763dffc95d404d0901eef4',
    messagingSenderId: '867722950685',
    projectId: 'todo-project-codesangam',
    authDomain: 'todo-project-codesangam.firebaseapp.com',
    storageBucket: 'todo-project-codesangam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHrfjBZCCDFW7ZumKKsEXdMmOqlVmsbCE',
    appId: '1:867722950685:android:572b62c180c39ef701eef4',
    messagingSenderId: '867722950685',
    projectId: 'todo-project-codesangam',
    storageBucket: 'todo-project-codesangam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFsl637GAON6za_q-4xufkOZU7Bh4K88s',
    appId: '1:867722950685:ios:25a0b177f7e4953501eef4',
    messagingSenderId: '867722950685',
    projectId: 'todo-project-codesangam',
    storageBucket: 'todo-project-codesangam.appspot.com',
    iosBundleId: 'com.example.spaceLabTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFsl637GAON6za_q-4xufkOZU7Bh4K88s',
    appId: '1:867722950685:ios:be3ba60cbbea420701eef4',
    messagingSenderId: '867722950685',
    projectId: 'todo-project-codesangam',
    storageBucket: 'todo-project-codesangam.appspot.com',
    iosBundleId: 'com.example.spaceLabTasks.RunnerTests',
  );
}
